language: python

python:
  - "3.7"

services:
  - rabbitmq

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - pytest -cov=rabbit_clients tests
  - pylint rabbit_clients
